name: "Push images on merge to master"
on:
  push:
    branches:
      - mb
jobs:
  build-and-push-amd64-device-plugin:
    if: github.repository_owner == 'MangoBoost'
    name: Image push AMD64
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/mangoboost/sriov-network-device-plugin
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push sriov-network-device-plugin
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
          file: images/Dockerfile
